concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner-1"
  url = "https://gitlab.devops-heroes.com"
  id = 2
  token = "glrt-t1_RQY3Z2nXosoxmkdh4zTD"
  token_obtained_at = 2025-03-29T15:48:59Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = true
    image = "alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    network_mode = "devops-heroes_gitlab"
    volumes = [
        "/var/run/docker.sock:/var/run/docker.sock", 
        "/cache",
        "devops-heroes_certificates:/etc/gitlab-runner/certs:ro"
    ]
    shm_size = 0
    network_mtu = 0
