name: devops-heroes

volumes:
  gitlab-data: {}
  gitlab-logs: {}

secrets:
  gitlab_root_password:
    file: ./volumes/gitlab/config/root_password.txt

networks:
  gitlab:
    driver: bridge

services:
  certificate_authority:
    image: alpine/openssl
    container_name: certificate_authority
    volumes:
      - ./volumes/certificate_authority/data:/ca
      - ./volumes/certificate_authority/config/openssl.cnf:/etc/ssl/openssl.cnf
      - ./volumes/certificate_authority/script/generate_certs.sh:/generate_certs.sh
    entrypoint: "/generate_certs.sh"

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - ./volumes/gitlab/config/gitlab.rb:/etc/gitlab/gitlab.rb
      - ./volumes/certificate_authority/data/certs/ca.crt:/etc/gitlab/trusted-certs/ca.crt
      - ./volumes/certificate_authority/data/certs/gitlab.devops-heroes.com.crt:/etc/gitlab/ssl/gitlab.devops-heroes.com.crt
      - ./volumes/certificate_authority/data/private/gitlab.devops-heroes.com.key:/etc/gitlab/ssl/gitlab.devops-heroes.com.key
    ports:
      - "39000:80"
      - "22:22"
      - "443:443"
    secrets:
      - gitlab_root_password
    networks:
      - gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.devops-heroes.com`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    depends_on:
      certificate_authority:
        condition: service_completed_successfully
    restart: unless-stopped

  gitlab-runner-1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-1
    volumes:
      - ./volumes/gitlab-runner/config/runner-config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/certificate_authority/data/certs/ca.crt:/etc/gitlab-runner/certs/ca.crt:ro
    networks:
      - gitlab
    environment:
      - TZ=Europe/Rome
    labels:
      - "traefik.enable=false"
    depends_on:
      gitlab:
        condition: service_healthy
    restart: unless-stopped

  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    depends_on:
      certificate_authority:
        condition: service_completed_successfully
    restart: unless-stopped