name: devops-heroes

volumes:
  gitlab-data: {}
  gitlab-logs: {}

secrets:
  gitlab_root_password:
    file: ./volumes/gitlab/config/root_password.txt

networks:
  gitlab:
    driver: bridge

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - ./volumes/gitlab/config/gitlab.rb:/etc/gitlab/gitlab.rb
    ports:
      - "39000:80"
      - "22:22"
      - "443:443"
    secrets:
      - gitlab_root_password
    networks:
      - gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.devops-heroes.com`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    restart: unless-stopped

  gitlab-runner-1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-1
    volumes:
      - ./volumes/gitlab-runner/config/runner-config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    environment:
      - TZ=Europe/Rome
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    restart: unless-stopped