## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: true

log:
  level: WARN

# enable dashboard on 8080 with auth
api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: true
    watch: true
  file:
    fileName: /etc/traefik/traefik.yaml
    watch: true

# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

## DYNAMIC CONFIG
tls:
  certificates:
    - certFile: /etc/traefik/certs/ca.crt
      keyFile: /etc/traefik/private/ca.key
    - certFile: /etc/traefik/certs/gitlab.devops-heroes.com.crt
      keyFile: /etc/traefik/private/gitlab.devops-heroes.com.key
    - certFile: /etc/traefik/certs/registry.devops-heroes.com.crt
      keyFile: /etc/traefik/private/registry.devops-heroes.com.key
# when testing certs, enable this so traefik doesn't use 
# it's own self signed. By default if it can't find a matching
# cert, it'll just create it's own which will cause cert warnings
# in browser
  # options:
    # default:
      # sniStrict: true

